id: "016"
title: "Test mix-minus with multiple callers"
component: "integration"
estimated_hours: 4

context: |
  Validate that mix-minus works correctly with multiple callers simultaneously.
  This is the "does it actually work?" test for the core feature.

  If this passes, OpenStudio delivers on its primary promise.

depends_on: ["015"]

acceptance_criteria:
  - Test with 3 hosts + 3 callers (6 participants total)
  - Each participant hears all others EXCEPT themselves
  - No echo or feedback reported by any participant
  - Audio quality is clear (no dropouts, distortion, or artifacts)
  - Mix-minus remains stable for 10+ minute session
  - Participants can join/leave without breaking mix-minus for others
  - Return feed latency acceptable (<200ms glass-to-glass)

files_to_create:
  - docs/testing/mix-minus-test-protocol.md

files_to_modify: []

tests_required:
  - "Manual: 6-person test session following test protocol"
  - "Manual: Each person confirms they don't hear themselves"
  - "Manual: Host asks each participant to speak, verifies everyone else hears them"
  - "Manual: Monitor for echo/feedback during conversation"
  - "Manual: Measure latency (clap test - time from clap to hearing it)"

references:
  - memory-bank/systemPatterns.md (Mix-Minus per Caller)
  - memory-bank/productContext.md (Clear audio - No echo or feedback issues)
  - memory-bank/techContext.md (Performance Targets - Latency)

notes: |
  Test protocol document should include:

  1. Setup:
     - 6 participants with headphones (prevent acoustic feedback)
     - Quiet environment (minimize background noise)
     - Chrome browser (primary target)

  2. Test procedure:
     - All join same room
     - Each person speaks their name
     - Host confirms each person heard by others
     - Each person confirms they don't hear themselves

  3. Edge cases to test:
     - Participant joins mid-session
     - Participant leaves mid-session
     - High audio levels (shouting)
     - Low audio levels (whisper)
     - Multiple people speaking simultaneously

  4. Success criteria:
     - Zero instances of self-echo
     - Audio quality rated "good" or better by all
     - No technical issues requiring reconnection

  If issues found, debug using chrome://webrtc-internals to inspect:
  - Track states
  - Audio levels
  - Connection quality
